name: Scheduled Python Job

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:
    inputs:
      run-now:
        description: 'Run the job now'
        required: true
        default: 'false'
      schedule-time:
        description: 'Schedule time (e.g., "in 1 hour", "2023-08-15T10:00:00")'
        required: false
        default: ''

jobs:
  schedule-or-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Schedule future run
        if: github.event.inputs.run-now != 'true' && github.event.inputs.schedule-time != ''
        uses: austenstone/schedule@v1.3
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          workflow: ${{ github.workflow }}
          date: ${{ github.event.inputs.schedule-time }}

      - name: Set up Python
        if: github.event.inputs.run-now == 'true' || github.event_name == 'schedule'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: github.event.inputs.run-now == 'true' || github.event_name == 'schedule'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        if: github.event.inputs.run-now == 'true' || github.event_name == 'schedule'
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py

      - name: Commit and push changes
        if: github.event.inputs.run-now == 'true' || github.event_name == 'schedule'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated by scheduled job" --allow-empty)
          git push
