name: 📅 Schedule Workflow Dispatch

on:
  schedule:
    - cron: '50 0 * * *' # every hour
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 hour'

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/schedule@v1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          date: ${{ github.event.inputs.date }}
          workflow: 'run_main.yml'
          timezone: 'US/Central'
          wait-ms: 45000
